server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test_flowable?useSSL=false&characterEncoding=utf-8&useUnicode=true&serverTimezone=Asia/Shanghai&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: 123456
flowable:
  # 关闭定时任务JOB
  # 关闭异步，不关闭历史数据的插入就是异步的，会在同一个事物里面，无法回滚
  # 开发可开启会提高些效率，上线需要关闭
  async-executor-activate: false
  # 将databaseSchemaUpdate设置为true,当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  database-schema-update: true
  # 自动部署验证设置:true-开启（默认）、false-关闭
  check-process-definitions: true
  labelFontName: 宋体
  activityFontName: 宋体
  annotationFontName: 宋体

pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true

logging:
  level:
    org:
      flowable: debug
    com:
      lzw:
        flowablespringboot:
              mapper: debug